name: Feature Request
description: Suggest a new feature or enhancement.
labels: ["enhancement"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Searched existing issues
      description: Search existing issues to avoid duplicates.
      options:
        - label: I have searched existing issues for duplicates.
          required: true

  - type: checkboxes
    id: willing
    attributes:
      label: Willing to contribute
      options:
        - label: I am willing to submit a pull request for this.
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
