#!/usr/bin/env python3
"""
Generate the reference pages of the documentation (Markdown, for MkDocs /
Read the Docs) from the sources of Lektra:

    commands.md        the commands, from Lektra's command registration
    configuration.md   the options, from the doc comments of include/Config.hpp
    lua_api.md         the Lua API, from the LuaLS stubs in stubs/lua/

The parsing is done by doc_commands.py, doc_config.py and doc_lua_api.py, the
scripts that also feed the website (JSON); this one only writes Markdown.

Usage:
    python scripts/gen_docs_md.py [--out DIR]

DIR defaults to docs/reference. The files are generated: do not edit them.
"""

import argparse
import html
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import doc_commands  # noqa: E402
import doc_config  # noqa: E402
import doc_lua_api  # noqa: E402


# ── Helpers ───────────────────────────────────────────────────────────────────


def project_version() -> str:
    """The version in CMakeLists.txt (project(lektra VERSION x.y.z))."""
    text = (ROOT / "CMakeLists.txt").read_text()
    m = re.search(r"project\(\s*lektra\s+VERSION\s+([0-9][0-9.]*)", text, re.I)
    return m.group(1) if m else "unknown"


def header(source: str, version: str) -> str:
    return (
        f"<!-- Generated by scripts/gen_docs_md.py from {source} "
        f"(Lektra {version}). Do not edit. -->\n\n"
    )


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


class Anchors:
    """Stable, unique heading ids, so that a page can be linked to."""

    def __init__(self):
        self.used: dict[str, int] = {}

    def make(self, *parts: str) -> str:
        base = slug("-".join(p for p in parts if p)) or "x"
        n = self.used.get(base, 0)
        self.used[base] = n + 1
        return base if n == 0 else f"{base}-{n + 1}"


def code(text: str) -> str:
    """Inline code that survives a backtick inside it."""
    text = str(text)
    if "`" in text:
        return f"`` {text} ``"
    return f"`{text}`"


def md_text(text: str) -> str:
    """Text written in Markdown (the Lua stubs): a "<" that starts something
    like <number> is shown as text instead of being taken for an HTML tag.
    Code spans are left as they are."""
    parts = re.split(r"(`[^`]*`)", str(text))
    return "".join(
        part if part.startswith("`") else re.sub(r"<(?=[a-zA-Z/])", "&lt;", part)
        for part in parts
    )


def cell(text: str) -> str:
    """Text for a table cell: no pipes, no line breaks."""
    return md_text(text).replace("|", "\\|").replace("\n", "<br>").strip()


# The doc comments of Config.hpp are written with a little HTML.
_PRE = re.compile(r"<pre[^>]*>(.*?)</pre>", re.S | re.I)
_KNOWN_TAGS = {"pre", "code", "b", "strong", "i", "em", "a", "br", "li", "ul",
               "ol", "p"}


def html_to_md(text: str) -> str:
    if not text:
        return ""

    # code blocks first, so that nothing below touches what is inside them
    blocks: list[str] = []

    def keep_pre(m):
        body = re.sub(r"</?[a-zA-Z][^>]*>", "", m.group(1))
        blocks.append("```\n" + html.unescape(body).strip("\n") + "\n```")
        return f"\n\n\x00{len(blocks) - 1}\x00\n\n"

    t = _PRE.sub(keep_pre, text)

    # a "<" that does not start one of the known tags is text (e.g. <type>)
    def escape_unknown(m):
        name = m.group(2).lower()
        return m.group(0) if name in _KNOWN_TAGS else "&lt;" + m.group(0)[1:]

    t = re.sub(r"<(/?)([a-zA-Z][a-zA-Z0-9]*)([^>]*)>", escape_unknown, t)

    # attributes (class="inline"...) do not matter, except the link target
    t = re.sub(r"<(code|b|strong|i|em|li|ul|ol|p|br)\b[^>]*?(/?)>", r"<\1\2>", t,
               flags=re.I)

    t = re.sub(r"<code>(.*?)</code>",
               lambda m: code(html.unescape(m.group(1))), t, flags=re.S | re.I)
    t = re.sub(r"</?(b|strong)>", "**", t, flags=re.I)
    t = re.sub(r"</?(i|em)>", "*", t, flags=re.I)
    t = re.sub(r'<a\s+[^>]*href="([^"]*)"[^>]*>(.*?)</a>', r"[\2](\1)", t,
               flags=re.S | re.I)
    t = re.sub(r"<br\s*/?>", "  \n", t, flags=re.I)
    t = re.sub(r"</?(ul|ol)>", "\n\n", t, flags=re.I)
    t = re.sub(r"<li>", "\n- ", t, flags=re.I)
    t = re.sub(r"</li>", "", t, flags=re.I)
    t = re.sub(r"</?p>", "\n\n", t, flags=re.I)

    # tidy: one space inside lines, at most one blank line between blocks
    lines = [re.sub(r"[ \t]+", " ", ln).strip() if not ln.startswith("- ")
             else "- " + re.sub(r"[ \t]+", " ", ln[2:]).strip()
             for ln in t.split("\n")]
    t = "\n".join(lines)
    t = re.sub(r"\n{3,}", "\n\n", t).strip()

    for i, block in enumerate(blocks):
        t = t.replace(f"\x00{i}\x00", block)
    return t


# ── Commands ──────────────────────────────────────────────────────────────────


def render_commands(version: str) -> str:
    commands = doc_commands.extract_all(str(ROOT / "src"))
    commands.sort(key=lambda c: c[0])

    out = [header("the command registrations in src/", version)]
    out.append("# Commands\n")
    out.append(
        "Every command can be run from the command palette, bound to a key "
        "with `lektra.keymap.set` or `[keybindings]`, or run from Lua with "
        "`lektra.cmd.execute(name, args)`. Run one from the command line with "
        "`lektra --command \"name args\"`.\n"
    )
    out.append(f"There are **{len(commands)}** commands.\n")
    out.append("| Command | Description |")
    out.append("|---|---|")
    for name, desc in commands:
        out.append(f"| {code(name)} | {cell(desc)} |")
    return "\n".join(out) + "\n"


# ── Configuration ─────────────────────────────────────────────────────────────


def section_title(name: str) -> str:
    """How a table is written in config.toml: lower case, and a template such
    as [Type] (any annotation kind) as <type>."""
    return re.sub(r"\[([^\]]*)\]", r"<\1>", name).lower()


def admonition(kind: str, text: str) -> str:
    """A Material admonition (a highlighted box) around Markdown text."""
    body = html_to_md(text)
    indented = "\n".join(("    " + line) if line else "" for line in body.split("\n"))
    return f"!!! {kind}\n\n{indented}\n"


def render_configuration(version: str) -> str:
    parser = doc_config.Parser()
    sections = parser.parse(str(ROOT / "include" / "Config.hpp"))
    anchors = Anchors()

    # the ids are made in order, so the index links to the same ids as the headings
    ids = [anchors.make("section", sec["name"]) for sec in sections]
    anchors = Anchors()
    for sec in sections:
        anchors.make("section", sec["name"])

    out = [header("include/Config.hpp", version)]
    out.append("# Configuration\n")
    out.append(
        "Options are set in `config.toml` (one table per section, such as "
        "`[page]`) or from Lua with `lektra.opt.<section>.<option>`. "
        "Each option shows its type, its default value and the release it "
        "appeared in.\n"
    )

    for sec, sid in zip(sections, ids):
        name = sec["name"]
        out.append(f"## {code(section_title(name))} {{#{sid} .cfg-section}}\n")

        if sec.get("section_added"):
            out.append(f"*{sec['section_added']}*{{ .opt-added }}\n")
        if sec.get("section_desc"):
            out.append(html_to_md(sec["section_desc"]) + "\n")
        if sec.get("section_note"):
            out.append(admonition("note", sec["section_note"]))

        for f in sec["fields"]:
            fid = anchors.make(name, f["name"])
            out.append(f"### {code(f['name'])} {{#{fid} .opt}}\n")

            badges = []
            if f.get("type"):
                badges.append(f"{code(f['type'])}{{ .opt-type }}")
            if f.get("default") not in (None, ""):
                badges.append(f"{code(f['default'])}{{ .opt-default }}")
            if f.get("added"):
                badges.append(f"*{f['added']}*{{ .opt-added }}")
            if badges:
                out.append(" ".join(badges) + "\n")

            if f.get("desc"):
                out.append(html_to_md(f["desc"]) + "\n")
            if f.get("choice"):
                choices = [c.strip() for c in f["choice"].split(",") if c.strip()]
                if choices and all(" " not in c and "<" not in c for c in choices):
                    out.append("**Choices:** "
                               + " ".join(f"{code(c)}{{ .opt-choice }}" for c in choices)
                               + "\n")
                else:
                    out.append("**Choices:** " + html_to_md(f["choice"]) + "\n")
            if f.get("note"):
                out.append(admonition("note", f["note"]))

    return "\n".join(out) + "\n"


# ── Lua API ───────────────────────────────────────────────────────────────────


def render_entry(entry: dict, level: str, anchors: Anchors, owner: str) -> list[str]:
    """A function or a method: its signature, text, parameters and result."""
    out = []
    aid = anchors.make(owner, entry["name"])
    out.append(f"{level} {code(entry['name'])} {{#{aid}}}\n")
    out.append("```lua\n" + entry["sig"] + "\n```\n")
    if entry.get("desc"):
        out.append(md_text(entry["desc"]) + "\n")
    if entry.get("params"):
        out.append("| Parameter | Type | Description |")
        out.append("|---|---|---|")
        for p in entry["params"]:
            out.append(f"| {code(p['name'])} | {code(p['type'])} | {cell(p.get('desc', ''))} |")
        out.append("")
    if entry.get("returns"):
        out.append(f"**Returns:** {md_text(entry['returns'])}\n")
    return out


def render_lua_api(version: str) -> str:
    modules = doc_lua_api.collect_modules(str(ROOT / "stubs" / "lua"))
    anchors = Anchors()

    out = [header("stubs/lua/*.lua", version)]
    out.append("# Lua API\n")
    out.append(
        "The `lektra` table is available in `init.lua` and in scripts. The "
        "stubs these pages are made from are installed to "
        "`/usr/share/lektra/lua/` (LuaLS: add the folder as a library for "
        "completion). Lua here is LuaJIT, that is Lua 5.1 with extensions.\n"
    )
    out.append("## Modules\n")
    for mod in modules:
        out.append(f"- [{code(mod['module'])}](#{anchors.make('module', mod['module'])})")
    out.append("")

    # the anchors of the module headings were made above, in the same order
    anchors = Anchors()
    for mod in modules:
        mid = anchors.make("module", mod["module"])
        out.append(f"## {code(mod['module'])} {{#{mid}}}\n")
        if mod.get("module_desc"):
            out.append(md_text(mod["module_desc"]) + "\n")

        for fn in mod["functions"]:
            out += render_entry(fn, "###", anchors, mod["module"])

        for cls in mod["classes"]:
            cid = anchors.make("class", cls["name"])
            out.append(f"### Class {code(cls['name'])} {{#{cid}}}\n")
            if cls.get("desc"):
                out.append(md_text(cls["desc"]) + "\n")
            if cls.get("fields"):
                out.append("| Field | Type | Description |")
                out.append("|---|---|---|")
                for f in cls["fields"]:
                    out.append(f"| {code(f['name'])} | {code(f['type'])} | {cell(f.get('desc', ''))} |")
                out.append("")
            for method in cls["methods"]:
                out += render_entry(method, "####", anchors, cls["name"])

    return "\n".join(out) + "\n"


# ── Index ─────────────────────────────────────────────────────────────────────


def render_index(version: str) -> str:
    out = [header("the sources", version)]
    out.append("# Reference\n")
    out.append(f"Generated from the sources of Lektra {version}.\n")
    out.append("- [Commands](commands.md): everything the command palette can run")
    out.append("- [Configuration](configuration.md): every option of `config.toml`")
    out.append("- [Lua API](lua_api.md): the `lektra` scripting API")
    return "\n".join(out) + "\n"


def generate(out_dir: Path) -> list[Path]:
    """Writes the pages to out_dir; returns the files whose content changed.

    A file with the same content is left alone, so that a watcher of the output
    folder (mkdocs serve) is not woken up for nothing."""
    out_dir.mkdir(parents=True, exist_ok=True)
    version = project_version()

    pages = {
        "index.md": render_index(version),
        "commands.md": render_commands(version),
        "configuration.md": render_configuration(version),
        "lua_api.md": render_lua_api(version),
    }
    changed = []
    for name, text in pages.items():
        path = out_dir / name
        if path.exists() and path.read_text() == text:
            continue
        path.write_text(text)
        changed.append(path)
    return changed


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the Markdown reference pages.")
    ap.add_argument("--out", default=str(ROOT / "docs" / "reference"),
                    help="folder to write to (default: docs/reference)")
    args = ap.parse_args()

    out_dir = Path(args.out)
    changed = generate(out_dir)
    for path in changed:
        print(f"wrote {path} ({len(path.read_text().splitlines())} lines)")
    if not changed:
        print(f"{out_dir} is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
